nohup python running_files/train_end2end_hep2.py \
    --model pix2pix \
    --is_train True \
    --cuda True \
    --gpu_ids 0 \
    --cuda_index 0 \
    --dataroot /user/apoli/GenSeg/data/HEp-2_specimen \
    --amp \
    --init_type kaiming \
    --loss_lambda 1.0 \
    --n_epochs 50 \
    --lr 2e-6 \
    --arch_lr 1e-6 \
    --classes 1 \
    --output_nc 1 \
    --input_nc 1 \
    --batch_size 32 \
    --seg_model unet \
    --unet_learning_rate 1e-4 \
